name: Publish Snapshot builds

on:
  push:
    branches:
      - main

jobs:
  publish_snapshot:
    name: Snapshot build and publish
    runs-on: macos-latest
    steps:
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
            distribution: 'temurin'
            cache: gradle

      - name: Snapshot build
        run: ./gradlew assemble compileKotlinIosArm64 compileKotlinIosX64

      - name: Verify library sources
        run: ./gradlew detektAll ktlintCheck lintRelease

      - name: Publish to Sonatype
        run: ./gradlew publishReleasePublicationToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SNAPSHOT: true